apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgeewesr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgeewesr
  template:
    metadata:
      labels:
        app: dgeewesr
    spec:
      containers:
      - image: okteto.dev/dgeewesr:latest
        name: dgeewesr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1623684f-8216-405c-b884-ad6fd5920190"
        - name: Vless_Path
          value: "/vdgfdry53w5"
        - name: Vmess_UUID
          value: "e1112bfa-d5e0-433c-abd6-d10747dba648"
        - name: Vmess_Path
          value: "/sdfyrtq243wsd"
        - name: Share_Path
          value: "/v2link"
